### PR TITLE
Add script to convert requested icons to make them easier to cusconify

### PR DESCRIPTION
**Pull request by jm355**
https://github.com/MiepHD/cuscon/issues/14

### CODE REVIEW

**Comment by MiepHD** [comment]
Thanks for that script that'll be very helpful but could you change it so that it doesn't output every single step and instead add a possibility to convert a full folder? (The output should go into `/get` with the original filenames)

**Comment by MiepHD** [comment]
There are some things that seem to be wrong.
It shouldn't just remove the background around the image but also in the image. (asiacell)
bordered_new_asiacell
asiacell
Also it won't fill white spaces with the background color neither with floodfill nor with replace
new_videos
bordered_new_videos

**Comment by jm355** [comment]
With the latest version, I ran `./cusconify.sh asiacell.png 256 0 25 75 replace` and got this: 
new_asiacell

I changed it to put the intermediate images into a temporary folder, since sometimes the final result isn't very good but an intermediate step can be worked with easier than the initial icon, or you can run the script on an intermediate image and it turns out pretty good.

For simple icons like that, it probably makes sense to set up a different script, or just use the background color the script prints out to manually fill the white center

**Comment by MiepHD** [comment]
Why would the final icon not be 512x512?

**Comment by MiepHD** [comment]
Please add an option to replace white with the background color

**Comment by MiepHD** [comment]
> For simple icons like that, it probably makes sense to set up a different script, or just use the background color the script prints out to manually fill the white center

Why can't the script do that?

**Comment by jm355** [comment]
> Why would the final icon not be 512x512?

The way I had it could in theory stretch the icon to be 512x512 without preserving the aspect ratio, I changed it to be guaranteed to respect the aspect ratio

**Comment by MiepHD** [comment]
Ah, okay

**Comment by jm355** [comment]
> > For simple icons like that, it probably makes sense to set up a different script, or just use the background color the script prints out to manually fill the white center
> 
> Why can't the script do that?

I tried to figure out a way to store the background color to be used to replace other colors, but I couldn't find a good way to do it without a bunch of text manipulation. Also, some icons it doesn't make sense to replace all the white with the background color, and some icons use a gradient for the background. 

So I figured the easiest way was for the script to print colors around the edge of the image, to give the rgb of the background image, and then let the user manually fill spots that they think should be the background color.

If you know the color you want to replace and the new color you want it to be it's pretty easy, I'll have the script print the command to do it so it can be run as a second step

**Comment by MiepHD** [comment]
Could you copy the white to a dedicated layer, then recolor that layer, remove the background in the other layer and merge then together? (Just an idea)

**Comment by jm355** [comment]
I'm not sure if imagemagick has layer stuff like that. It probably does but I'm not sure how to do that. I had it print out the command to replace white with the background color though, so just running that after should work.

**Review by MiepHD — APPROVED** [review]

**Comment by MiepHD** [comment]
Thanks for your contribution, this will come in handy.

**Pull request merged**
